// Données fictives pour l'application GMAO
// Ce fichier remplace complètement Supabase

export const mockProfils = [
    { id: '1', nom: 'El Amrani', prenom: 'Youssef', email: 'youssef.elamrani@gmao.ma', telephone: '0661234567', actif: true, created_at: '2024-01-15T10:00:00Z' },
    { id: '2', nom: 'Bennani', prenom: 'Fatima', email: 'fatima.bennani@gmao.ma', telephone: '0672345678', actif: true, created_at: '2024-01-16T10:00:00Z' },
    { id: '3', nom: 'Alaoui', prenom: 'Mohammed', email: 'mohammed.alaoui@gmao.ma', telephone: '0683456789', actif: true, created_at: '2024-01-17T10:00:00Z' },
    { id: '4', nom: 'Idrissi', prenom: 'Amina', email: 'amina.idrissi@gmao.ma', telephone: '0694567890', actif: true, created_at: '2024-01-18T10:00:00Z' },
    { id: '5', nom: 'Tazi', prenom: 'Omar', email: 'omar.tazi@gmao.ma', telephone: '0605678901', actif: true, created_at: '2024-01-19T10:00:00Z' },
    { id: '6', nom: 'Benjelloun', prenom: 'Sanaa', email: 'sanaa.benjelloun@gmao.ma', telephone: '0616789012', actif: true, created_at: '2024-01-20T10:00:00Z' },
    { id: '7', nom: 'Cherkaoui', prenom: 'Rachid', email: 'rachid.cherkaoui@gmao.ma', telephone: '0627890123', actif: true, created_at: '2024-01-21T10:00:00Z' },
    { id: '8', nom: 'Fassi', prenom: 'Laila', email: 'laila.fassi@gmao.ma', telephone: '0638901234', actif: true, created_at: '2024-01-22T10:00:00Z' },
];

export const mockCategoriesEquipement = [
    { id: '1', nom: 'Pneumatique', description: 'Équipements pneumatiques', icone: '💨' },
    { id: '2', nom: 'Hydraulique', description: 'Équipements hydrauliques', icone: '🔧' },
    { id: '3', nom: 'Électrique', description: 'Équipements électriques', icone: '⚡' },
    { id: '4', nom: 'Mécanique', description: 'Équipements mécaniques', icone: '⚙️' },
    { id: '5', nom: 'Convoyage', description: 'Systèmes de convoyage', icone: '🔄' },
];

export const mockSites = [
    { id: '1', nom: 'Site Principal', adresse: '123 Rue de l\'Industrie', ville: 'Casablanca', code_postal: '20000', pays: 'Maroc', actif: true },
    { id: '2', nom: 'Site Secondaire', adresse: '456 Avenue de la Production', ville: 'Rabat', code_postal: '10000', pays: 'Maroc', actif: true },
];

export const mockEquipements = [
    {
        id: '1',
        code: 'EQ-CAS-001',
        nom: 'Compresseur ALM GA45',
        categorie_id: '1',
        marque: 'ALM',
        modele: 'GA45',
        numero_serie: 'ALM-123456',
        annee_fabrication: 2020,
        date_mise_service: '2020-06-15',
        site_id: '1',
        statut: 'en_service',
        criticite: 'haute',
        valeur_achat: 450000,
        description: 'Compresseur d\'air principal - Unité Casablanca',
        actif: true,
        created_at: '2024-01-10T08:00:00Z',
        categorie: mockCategoriesEquipement[0],
        site: mockSites[0]
    },
    {
        id: '2',
        code: 'EQ-CAS-002',
        nom: 'Pompe Hydraulique MAGHREB',
        categorie_id: '2',
        marque: 'Maghreb Hydraulique',
        modele: 'MH-7V',
        numero_serie: 'MH-789012',
        annee_fabrication: 2019,
        date_mise_service: '2019-11-20',
        site_id: '1',
        statut: 'en_maintenance',
        criticite: 'critique',
        valeur_achat: 280000,
        description: 'Pompe hydraulique principale - Unité Casablanca',
        actif: true,
        created_at: '2024-01-11T09:00:00Z',
        categorie: mockCategoriesEquipement[1],
        site: mockSites[0]
    },
    {
        id: '3',
        code: 'EQ-RAB-003',
        nom: 'Convoyeur à bande MAROC',
        categorie_id: '5',
        marque: 'Siemens Maroc',
        modele: 'CB-2000',
        numero_serie: 'SIM-345678',
        annee_fabrication: 2021,
        date_mise_service: '2021-03-10',
        site_id: '2',
        statut: 'en_service',
        criticite: 'moyenne',
        valeur_achat: 350000,
        description: 'Convoyeur principal - Unité Rabat',
        actif: true,
        created_at: '2024-01-12T10:00:00Z',
        categorie: mockCategoriesEquipement[4],
        site: mockSites[1]
    },
    {
        id: '4',
        code: 'EQ-CAS-004',
        nom: 'Armoire Électrique TANGER',
        categorie_id: '3',
        marque: 'Schneider Maroc',
        modele: 'TR-400',
        numero_serie: 'SM-901234',
        annee_fabrication: 2018,
        date_mise_service: '2018-08-25',
        site_id: '1',
        statut: 'en_service',
        criticite: 'critique',
        valeur_achat: 520000,
        description: 'Transformateur électrique principal',
        actif: true,
        created_at: '2024-01-13T11:00:00Z',
        categorie: mockCategoriesEquipement[2],
        site: mockSites[0]
    },
    {
        id: '5',
        code: 'EQ-RAB-005',
        nom: 'Moteur de Ligne AGADIR',
        categorie_id: '3',
        marque: 'ABB Maroc',
        modele: 'M3BP',
        numero_serie: 'AM-567890',
        annee_fabrication: 2022,
        date_mise_service: '2022-01-15',
        site_id: '2',
        statut: 'en_panne',
        criticite: 'haute',
        valeur_achat: 180000,
        description: 'Moteur de ligne de production - Rabat',
        actif: true,
        created_at: '2024-01-14T12:00:00Z',
        categorie: mockCategoriesEquipement[2],
        site: mockSites[1]
    },
    {
        id: '6',
        code: 'EQ-CAS-006',
        nom: 'Ventilateur Industriel FÈS',
        categorie_id: '4',
        marque: 'Fès Vent',
        modele: 'FV-100',
        numero_serie: 'FV-654321',
        annee_fabrication: 2023,
        date_mise_service: '2023-05-12',
        site_id: '1',
        statut: 'en_service',
        criticite: 'basse',
        valeur_achat: 45000,
        description: 'Système de ventilation zone 2',
        actif: true,
        created_at: '2024-02-10T08:00:00Z',
        categorie: mockCategoriesEquipement[3],
        site: mockSites[0]
    },
];

export const mockDemandesIntervention = [
    {
        id: '1',
        numero: 'DI-2026-001',
        equipement_id: '1',
        demandeur_id: '2',
        service_demandeur: 'Production',
        date_souhaitee: '2026-01-15',
        priorite: 'haute',
        type_demande: 'panne',
        titre: 'Fuite huile compresseur',
        description: 'Détection d\'une fuite d\'huile importante au niveau du carter du compresseur. Intervention urgente requise.',
        localisation: 'Atelier A, Zone 1',
        statut: 'nouvelle',
        created_at: '2026-01-02T08:30:00Z',
        equipement: mockEquipements[0],
        demandeur: mockProfils[1]
    },
    {
        id: '2',
        numero: 'DI-2026-002',
        equipement_id: '2',
        demandeur_id: '4',
        service_demandeur: 'Production',
        date_souhaitee: '2026-01-10',
        priorite: 'urgente',
        type_demande: 'panne',
        titre: 'Bruit anormal pompe hydraulique',
        description: 'La pompe hydraulique émet un bruit inhabituel et des vibrations anormales depuis ce matin.',
        localisation: 'Salle des machines',
        statut: 'en_evaluation',
        created_at: '2026-01-05T14:15:00Z',
        equipement: mockEquipements[1],
        demandeur: mockProfils[3]
    },
    {
        id: '3',
        numero: 'DI-2026-003',
        equipement_id: '3',
        demandeur_id: '3',
        service_demandeur: 'Logistique',
        date_souhaitee: '2026-01-20',
        priorite: 'normale',
        type_demande: 'amelioration',
        titre: 'Optimisation vitesse convoyeur',
        description: 'Demande d\'ajustement des paramètres du variateur pour augmenter la cadence.',
        localisation: 'Ligne de production Rabat',
        statut: 'approuvee',
        created_at: '2026-01-02T10:00:00Z',
        equipement: mockEquipements[2],
        demandeur: mockProfils[2]
    },
    {
        id: '4',
        numero: 'DI-2026-004',
        equipement_id: '5',
        demandeur_id: '1',
        service_demandeur: 'Ligne 2',
        date_souhaitee: '2026-01-08',
        priorite: 'urgente',
        type_demande: 'panne',
        titre: 'Surchauffe moteur ABB',
        description: 'Moteur bouillant au toucher, fumée détectée. Arrêt immédiat de la ligne.',
        localisation: 'Zone B, Étage 1',
        statut: 'convertie_ot',
        ordre_travail_id: '1',
        created_at: '2026-01-05T09:00:00Z',
        equipement: mockEquipements[4],
        demandeur: mockProfils[0]
    },
    {
        id: '5',
        numero: 'DI-2026-005',
        equipement_id: '6',
        demandeur_id: '8',
        service_demandeur: 'Qualité',
        date_souhaitee: '2026-01-25',
        priorite: 'basse',
        type_demande: 'autre',
        titre: 'Nettoyage des filtres de ventilation',
        description: 'La ventilation semble moins efficace, prévoir un nettoyage.',
        localisation: 'Bureaux Administratifs',
        statut: 'nouvelle',
        created_at: '2026-01-06T11:30:00Z',
        equipement: mockEquipements[5],
        demandeur: mockProfils[7]
    },
];

export const mockSpecialites = [
    { id: '1', nom: 'Mécanique', description: 'Maintenance mécanique' },
    { id: '2', nom: 'Électricité', description: 'Maintenance électrique' },
    { id: '3', nom: 'Hydraulique', description: 'Maintenance hydraulique' },
    { id: '4', nom: 'Pneumatique', description: 'Maintenance pneumatique' },
];

export const mockTechniciens = [
    {
        id: '1',
        profil_id: '1',
        matricule: 'TECH-001',
        specialite_id: '1',
        niveau: 'senior',
        taux_horaire: 85,
        disponible: true,
        date_embauche: '2018-01-15',
        profil: mockProfils[0],
        specialite: mockSpecialites[0]
    },
    {
        id: '2',
        profil_id: '5',
        matricule: 'TECH-002',
        specialite_id: '2',
        niveau: 'expert',
        taux_horaire: 120,
        disponible: true,
        date_embauche: '2015-03-20',
        profil: mockProfils[4],
        specialite: mockSpecialites[1]
    },
    {
        id: '3',
        profil_id: '7',
        matricule: 'TECH-003',
        specialite_id: '3',
        niveau: 'confirme',
        taux_horaire: 75,
        disponible: true,
        date_embauche: '2019-11-10',
        profil: mockProfils[6],
        specialite: mockSpecialites[2]
    },
    {
        id: '4',
        profil_id: '3',
        matricule: 'TECH-004',
        specialite_id: '4',
        niveau: 'junior',
        taux_horaire: 60,
        disponible: true,
        date_embauche: '2022-06-01',
        profil: mockProfils[2],
        specialite: mockSpecialites[3]
    },
    {
        id: '5',
        profil_id: '6',
        matricule: 'TECH-005',
        specialite_id: '1',
        niveau: 'confirme',
        taux_horaire: 80,
        disponible: true,
        date_embauche: '2020-02-15',
        profil: mockProfils[5],
        specialite: mockSpecialites[0]
    },
];

export const mockOrdresTravail = [
    {
        id: '1',
        numero: 'OT-MAR-2026-001',
        demande_id: '4',
        equipement_id: '5',
        type_maintenance: 'corrective',
        priorite: 'urgente',
        titre: 'Réparation moteur ABB',
        description: 'Remplacement des roulements et vérification bobinage',
        statut: 'en_cours',
        date_prevue_debut: '2026-01-05T08:00:00Z',
        date_prevue_fin: '2026-01-05T17:00:00Z',
        date_debut_reel: '2026-01-05T09:30:00Z',
        duree_prevue_heures: 8,
        technicien_id: '1',
        cout_main_oeuvre: 1200,
        cout_pieces: 3500,
        created_at: '2026-01-05T08:15:00Z',
        equipement: mockEquipements[4],
        technicien: mockTechniciens[0]
    },
    {
        id: '2',
        numero: 'OT-MAR-2026-002',
        demande_id: null,
        equipement_id: '1',
        type_maintenance: 'preventive',
        priorite: 'normale',
        titre: 'Maintenance préventive mensuelle',
        description: 'Entretien systématique du compresseur principal',
        statut: 'planifie',
        date_prevue_debut: '2026-01-20T09:00:00Z',
        date_prevue_fin: '2026-01-20T12:00:00Z',
        duree_prevue_heures: 3,
        technicien_id: '3',
        cout_main_oeuvre: 450,
        created_at: '2026-01-06T10:00:00Z',
        equipement: mockEquipements[0],
        technicien: mockTechniciens[2]
    },
    {
        id: '3',
        numero: 'OT-MAR-2026-003',
        demande_id: null,
        equipement_id: '4',
        type_maintenance: 'predictive',
        priorite: 'haute',
        titre: 'Analyse thermographique transformateur',
        description: 'Contrôle des points chauds sur les connexions',
        statut: 'en_cours',
        date_prevue_debut: '2026-01-06T14:00:00Z',
        date_prevue_fin: '2026-01-06T16:00:00Z',
        date_debut_reel: '2026-01-06T14:15:00Z',
        duree_prevue_heures: 2,
        technicien_id: '2',
        cout_main_oeuvre: 800,
        created_at: '2026-01-06T13:00:00Z',
        equipement: mockEquipements[3],
        technicien: mockTechniciens[1]
    },
];

export const mockPlansMaintenance = [
    {
        id: '1',
        equipement_id: '1',
        nom: 'Entretien mensuel compresseur',
        description: 'Vérification et entretien mensuel du compresseur (filtres, huile, courroies)',
        type_declenchement: 'calendrier',
        frequence_jours: 30,
        prochaine_date: '2026-02-15',
        duree_estimee_heures: 4,
        technicien_id: '1',
        actif: true,
        equipement: mockEquipements[0],
        technicien: mockTechniciens[0]
    },
    {
        id: '2',
        equipement_id: '2',
        nom: 'Maintenance trimestrielle pompe',
        description: 'Maintenance préventive trimestrielle des circuits hydrauliques',
        type_declenchement: 'calendrier',
        frequence_jours: 90,
        prochaine_date: '2026-04-01',
        duree_estimee_heures: 3,
        technicien_id: '3',
        actif: true,
        equipement: mockEquipements[1],
        technicien: mockTechniciens[2]
    },
    {
        id: '3',
        equipement_id: '4',
        nom: 'Inspection électrique semestrielle',
        description: 'Contrôle complet des armoires et transformateurs',
        type_declenchement: 'calendrier',
        frequence_jours: 180,
        prochaine_date: '2026-06-15',
        duree_estimee_heures: 6,
        technicien_id: '2',
        actif: true,
        equipement: mockEquipements[3],
        technicien: mockTechniciens[1]
    },
    {
        id: '4',
        equipement_id: '3',
        nom: 'Graissage automatique hebdomadaire',
        description: 'Vérification du système de graissage du convoyeur',
        type_declenchement: 'calendrier',
        frequence_jours: 7,
        prochaine_date: '2026-01-15',
        duree_estimee_heures: 1,
        technicien_id: '5',
        actif: true,
        equipement: mockEquipements[2],
        technicien: mockTechniciens[4]
    },
];

export const mockCategoriesPiece = [
    { id: '1', nom: 'Roulements', description: 'Roulements et paliers' },
    { id: '2', nom: 'Courroies', description: 'Courroies et transmissions' },
    { id: '3', nom: 'Filtres', description: 'Filtres et cartouches' },
    { id: '4', nom: 'Lubrifiants', description: 'Huiles et graisses' },
    { id: '5', nom: 'Joints', description: 'Joints et étanchéité' },
    { id: '6', nom: 'Électrique', description: 'Composants électriques' },
];

export const mockFournisseurs = [
    {
        id: '1',
        code: 'FRN-CAS-001',
        nom: 'Soremar Casablanca',
        type_fournisseur: 'pieces',
        adresse: 'Route de Tanger, Km 12',
        ville: 'Casablanca',
        telephone: '+212 522 34 56 78',
        email: 'sales@soremar.ma',
        contact_principal: 'Youssef El Filali',
        evaluation: 4.5,
        actif: true
    },
    {
        id: '2',
        code: 'FRN-RAB-002',
        nom: 'Maghreb Hydraulique',
        type_fournisseur: 'pieces',
        adresse: 'Zone Industrielle Gzenaya',
        ville: 'Tanger',
        telephone: '+212 539 98 76 54',
        email: 'contact@maghrebhydraulique.com',
        contact_principal: 'Abdelatif Mansouri',
        evaluation: 4.8,
        actif: true
    },
    {
        id: '3',
        code: 'FRN-MAR-003',
        nom: 'Maintenance Pro Maroc',
        type_fournisseur: 'services',
        adresse: 'Boulevard Abdelmoumen',
        ville: 'Casablanca',
        telephone: '+212 522 90 12 34',
        email: 'services@maintpro.ma',
        contact_principal: 'Khadija Amrani',
        evaluation: 4.2,
        actif: true
    },
    {
        id: '4',
        code: 'FRN-AGD-004',
        nom: 'Agadir Électricité Industrielle',
        type_fournisseur: 'mixte',
        adresse: 'Avenue Hassan II',
        ville: 'Agadir',
        telephone: '+212 528 22 33 44',
        email: 'info@agadirelec.ma',
        contact_principal: 'Saïd Bennani',
        evaluation: 4.0,
        actif: true
    },
];

export const mockPiecesRechange = [
    {
        id: '1',
        code: 'PR-001',
        designation: 'Roulement SKF 6205-2RS',
        categorie_id: '1',
        reference_fabricant: 'SKF-6205',
        unite: 'unite',
        stock_actuel: 25,
        stock_minimum: 10,
        stock_maximum: 50,
        point_commande: 15,
        emplacement: 'A1-01',
        prix_unitaire: 185,
        fournisseur_id: '1',
        critique: false,
        actif: true,
        categorie: mockCategoriesPiece[0],
        fournisseur: mockFournisseurs[0]
    },
    {
        id: '2',
        code: 'PR-002',
        designation: 'Courroie trapézoïdale A68',
        categorie_id: '2',
        reference_fabricant: 'GATES-A68',
        unite: 'unite',
        stock_actuel: 5,
        stock_minimum: 8,
        stock_maximum: 30,
        point_commande: 10,
        emplacement: 'A2-03',
        prix_unitaire: 129,
        fournisseur_id: '1',
        critique: true,
        actif: true,
        categorie: mockCategoriesPiece[1],
        fournisseur: mockFournisseurs[0]
    },
    {
        id: '3',
        code: 'PR-003',
        designation: 'Huile hydraulique HLP 46 (20L)',
        categorie_id: '4',
        reference_fabricant: 'SHELL-HLP46',
        unite: 'litre',
        stock_actuel: 80,
        stock_minimum: 40,
        stock_maximum: 200,
        point_commande: 60,
        emplacement: 'B1-02',
        prix_unitaire: 850,
        fournisseur_id: '2',
        critique: false,
        actif: true,
        categorie: mockCategoriesPiece[3],
        fournisseur: mockFournisseurs[1]
    },
    {
        id: '4',
        code: 'PR-004',
        designation: 'Filtre air compresseur',
        categorie_id: '3',
        reference_fabricant: 'ATLAS-F400',
        unite: 'unite',
        stock_actuel: 3,
        stock_minimum: 5,
        stock_maximum: 15,
        point_commande: 6,
        emplacement: 'A3-01',
        prix_unitaire: 450,
        fournisseur_id: '2',
        critique: true,
        actif: true,
        categorie: mockCategoriesPiece[2],
        fournisseur: mockFournisseurs[1]
    },
    {
        id: '5',
        code: 'PR-005',
        designation: 'Joint torique 50x3',
        categorie_id: '5',
        reference_fabricant: 'VITON-50x3',
        unite: 'unite',
        stock_actuel: 120,
        stock_minimum: 50,
        stock_maximum: 200,
        point_commande: 75,
        emplacement: 'C1-05',
        prix_unitaire: 12,
        fournisseur_id: '2',
        critique: false,
        actif: true,
        categorie: mockCategoriesPiece[4],
        fournisseur: mockFournisseurs[1]
    },
    {
        id: '6',
        code: 'PR-006',
        designation: 'Contacteur LC1D25',
        categorie_id: '6',
        reference_fabricant: 'SCHNEIDER-LC1D25',
        unite: 'unite',
        stock_actuel: 2,
        stock_minimum: 3,
        stock_maximum: 10,
        point_commande: 4,
        emplacement: 'D1-02',
        prix_unitaire: 650,
        fournisseur_id: '4',
        critique: true,
        actif: true,
        categorie: mockCategoriesPiece[5],
        fournisseur: mockFournisseurs[3]
    },
    {
        id: '7',
        code: 'PR-007',
        designation: 'Graisse multi-usage (1kg)',
        categorie_id: '4',
        reference_fabricant: 'TOTAL-MULTIS',
        unite: 'unite',
        stock_actuel: 15,
        stock_minimum: 5,
        stock_maximum: 30,
        point_commande: 10,
        emplacement: 'B1-05',
        prix_unitaire: 120,
        fournisseur_id: '1',
        critique: false,
        actif: true,
        categorie: mockCategoriesPiece[3],
        fournisseur: mockFournisseurs[0]
    },
    {
        id: '8',
        code: 'PR-008',
        designation: 'Disjoncteur 16A',
        categorie_id: '6',
        reference_fabricant: 'LEGRAND-16A',
        unite: 'unite',
        stock_actuel: 12,
        stock_minimum: 5,
        stock_maximum: 20,
        point_commande: 8,
        emplacement: 'D1-05',
        prix_unitaire: 85,
        fournisseur_id: '4',
        critique: false,
        actif: true,
        categorie: mockCategoriesPiece[5],
        fournisseur: mockFournisseurs[3]
    },
];



// Compteurs pour génération d'IDs
let nextEquipementId = mockEquipements.length + 1;
let nextDemandeId = mockDemandesIntervention.length + 1;
let nextOTId = mockOrdresTravail.length + 1;
let nextPieceId = mockPiecesRechange.length + 1;
let nextTechnicienId = mockTechniciens.length + 1;
let nextPlanId = mockPlansMaintenance.length + 1;

export function generateId(type: string): string {
    switch (type) {
        case 'equipement': return String(nextEquipementId++);
        case 'demande': return String(nextDemandeId++);
        case 'ot': return String(nextOTId++);
        case 'piece': return String(nextPieceId++);
        case 'technicien': return String(nextTechnicienId++);
        case 'plan': return String(nextPlanId++);
        default: return String(Date.now());
    }
}

// Helper pour simuler un délai async (optionnel)
export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
